# Generated by Django 3.0.8 on 2021-05-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='first_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='last_name',
            new_name='name',
        ),
    ]
