# Generated by Django 3.0.8 on 2021-05-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_api', '0002_auto_20210507_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='document',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='lastname',
        ),
    ]
